// Realistic seed data for the properties table. Images are Unsplash URLs that
// have been checked to resolve (HTTP 200). Categories match the home-page filter
// taxonomy; the home page derives its sections from these.
//
// `property_type` is the top-level navbar grouping: 'stay' | 'experience' |
// 'adventure'. The stays below omit it and default to 'stay' at insert time.

export const stays = [
  {
    title: 'Sunlit cliffside villa',
    location: 'Oia, Greece',
    description: 'Whitewashed villa carved into the caldera with a private infinity plunge pool and sweeping sunset views over the Aegean.',
    price_per_night: 342,
    rating: 4.97,
    review_count: 214,
    image_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    category: 'Luxury',
    dates: 'Oct 12 – 17',
    note: 'Rare find',
  },
  {
    title: 'Minimalist forest cabin',
    location: 'Hemsedal, Norway',
    description: 'Warm timber cabin tucked into pine forest, with a wood stove, floor-to-ceiling windows and trailheads at the door.',
    price_per_night: 210,
    rating: 4.89,
    review_count: 156,
    image_url: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?q=80&w=1200&auto=format&fit=crop',
    category: 'Cabins',
    dates: 'Nov 3 – 8',
    note: null,
  },
  {
    title: 'Rooftop loft with skyline view',
    location: 'Brooklyn, New York',
    description: 'Industrial loft with a private roof deck framing the Manhattan skyline, minutes from Williamsburg cafes and galleries.',
    price_per_night: 298,
    rating: 4.78,
    review_count: 389,
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
    category: 'City',
    dates: 'Oct 20 – 24',
    note: null,
  },
  {
    title: 'Adobe desert retreat',
    location: 'Marrakech, Morocco',
    description: 'Tranquil riad with a shaded courtyard, plunge pool and rooftop terrace overlooking the Atlas Mountains.',
    price_per_night: 165,
    rating: 4.94,
    review_count: 271,
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
    category: 'Countryside',
    dates: 'Dec 1 – 6',
    note: 'Guest favorite',
  },
  {
    title: 'Terraced rice-field bungalow',
    location: 'Ubud, Bali',
    description: 'Open-air bungalow perched over emerald rice terraces, with an outdoor rain shower and daily fresh fruit.',
    price_per_night: 96,
    rating: 4.91,
    review_count: 502,
    image_url: 'https://images.unsplash.com/photo-1518733057094-95b53143d2a7?q=80&w=1200&auto=format&fit=crop',
    category: 'Countryside',
    dates: 'Oct 9 – 14',
    note: null,
  },
  {
    title: 'Glass-walled lakeside cabin',
    location: 'Banff, Canada',
    description: 'Contemporary cabin on a glacial lake with a wraparound deck, canoe and uninterrupted Rocky Mountain reflections.',
    price_per_night: 275,
    rating: 4.86,
    review_count: 178,
    image_url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=1200&auto=format&fit=crop',
    category: 'Cabins',
    dates: 'Nov 15 – 19',
    note: null,
  },
  {
    title: 'A-frame chalet with sauna',
    location: 'Zermatt, Switzerland',
    description: 'Classic alpine A-frame with a private sauna and Matterhorn views, ski-in ski-out to the Zermatt slopes.',
    price_per_night: 410,
    rating: 4.98,
    review_count: 121,
    image_url: 'https://images.unsplash.com/photo-1518602164578-cd0074062767?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    dates: 'Dec 20 – 27',
    note: 'Rare find',
  },
  {
    title: 'Timber lodge above the treeline',
    location: 'Aspen, Colorado',
    description: 'Handcrafted timber lodge with a stone fireplace, hot tub and panoramic views over the Elk Mountains.',
    price_per_night: 355,
    rating: 4.87,
    review_count: 204,
    image_url: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    dates: 'Jan 2 – 7',
    note: null,
  },
  {
    title: 'Stone cottage in the highlands',
    location: 'Isle of Skye, Scotland',
    description: 'Restored crofter’s cottage with a peat fire, sheepskin throws and dramatic sea-cliff walks from the doorstep.',
    price_per_night: 148,
    rating: 4.9,
    review_count: 176,
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    dates: 'Oct 14 – 19',
    note: null,
  },
  {
    title: 'Ridge-top cabin with hot tub',
    location: 'Queenstown, New Zealand',
    description: 'Perched above Lake Wakatipu with a cedar hot tub, this cabin frames the Remarkables through full-height glass.',
    price_per_night: 289,
    rating: 4.93,
    review_count: 158,
    image_url: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    dates: 'Nov 9 – 14',
    note: null,
  },
  {
    title: 'Alpine glass cabin',
    location: 'Dolomites, Italy',
    description: 'A modern glass-fronted cabin among the Dolomite peaks, with heated floors and a terrace made for stargazing.',
    price_per_night: 265,
    rating: 4.85,
    review_count: 133,
    image_url: 'https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    dates: 'Dec 5 – 10',
    note: null,
  },
  {
    title: 'Wildflower meadow farmhouse',
    location: 'Salzkammergut, Austria',
    description: 'Alpine farmhouse ringed by wildflower meadows and lakes, with a farmhouse kitchen and cowbells in the distance.',
    price_per_night: 172,
    rating: 4.88,
    review_count: 97,
    image_url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1200&auto=format&fit=crop',
    category: 'Countryside',
    dates: 'Oct 23 – 28',
    note: null,
  },
  {
    title: 'Whitewashed beach house',
    location: 'Mykonos, Greece',
    description: 'Cycladic beach house steps from a quiet cove, with a sun-bleached terrace and a hammock strung between olive trees.',
    price_per_night: 260,
    rating: 4.92,
    review_count: 231,
    image_url: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
    category: 'Beach',
    dates: 'Oct 5 – 10',
    note: null,
  },
  {
    title: 'Overwater bungalow',
    location: 'Bora Bora, French Polynesia',
    description: 'Thatched bungalow suspended over a turquoise lagoon, with a glass floor panel and steps straight into the water.',
    price_per_night: 610,
    rating: 4.99,
    review_count: 98,
    image_url: 'https://images.unsplash.com/photo-1439130490301-25e322d88054?q=80&w=1200&auto=format&fit=crop',
    category: 'Islands',
    dates: 'Jan 8 – 13',
    note: 'Rare find',
  },
  {
    title: 'Palm-shaded surf cottage',
    location: 'Canggu, Bali',
    description: 'Relaxed cottage a short walk from the break, with an outdoor shower, board storage and a shaded plunge pool.',
    price_per_night: 88,
    rating: 4.83,
    review_count: 342,
    image_url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
    category: 'Beach',
    dates: 'Oct 18 – 23',
    note: null,
  },
  {
    title: 'Coral coast pool villa',
    location: 'Zanzibar, Tanzania',
    description: 'Swahili-style villa with a private pool, coral-stone walls and a rooftop for sundowners over the Indian Ocean.',
    price_per_night: 199,
    rating: 4.95,
    review_count: 143,
    image_url: 'https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?q=80&w=1200&auto=format&fit=crop',
    category: 'Pools',
    dates: 'Nov 2 – 7',
    note: null,
  },
  {
    title: 'Dune house on the shoreline',
    location: 'Outer Banks, USA',
    description: 'Weathered-cedar beach house set in the dunes, with a screened porch, outdoor shower and a boardwalk to the sand.',
    price_per_night: 231,
    rating: 4.8,
    review_count: 267,
    image_url: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?q=80&w=1200&auto=format&fit=crop',
    category: 'Beach',
    dates: 'Oct 27 – 31',
    note: null,
  },
  {
    title: 'Cliffside cove hideaway',
    location: 'Amalfi Coast, Italy',
    description: 'Pastel villa clinging to the cliffs above a hidden cove, with a lemon-tree terrace and steps down to the sea.',
    price_per_night: 385,
    rating: 4.96,
    review_count: 189,
    image_url: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=1200&auto=format&fit=crop',
    category: 'Beach',
    dates: 'Sep 30 – Oct 5',
    note: 'Guest favorite',
  },
]

// Experiences — host-led activities rather than places to sleep.
export const experiences = [
  {
    title: 'Sunset catamaran cruise',
    location: 'Santorini, Greece',
    description: 'Sail the caldera at golden hour with a small group, swim in volcanic hot springs and share a Greek meze dinner on deck as the sun drops behind Oia.',
    price_per_night: 95,
    rating: 4.96,
    review_count: 418,
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop',
    category: 'Islands',
    property_type: 'experience',
    dates: '5 hours · evenings',
    note: 'Guest favorite',
  },
  {
    title: 'Traditional tagine cooking class',
    location: 'Marrakech, Morocco',
    description: 'Shop the souk with a local chef, then cook a three-course Moroccan feast in a riad courtyard and sit down to eat everything you made.',
    price_per_night: 62,
    rating: 4.94,
    review_count: 287,
    image_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=1200&auto=format&fit=crop',
    category: 'City',
    property_type: 'experience',
    dates: '4 hours · daily',
    note: null,
  },
  {
    title: 'Tuscan vineyard tasting tour',
    location: 'Chianti, Italy',
    description: 'Walk the vine rows of a family estate, learn how Chianti Classico is made and taste five wines paired with olive oil, pecorino and cured meats.',
    price_per_night: 78,
    rating: 4.9,
    review_count: 203,
    image_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=1200&auto=format&fit=crop',
    category: 'Countryside',
    property_type: 'experience',
    dates: '3 hours · afternoons',
    note: null,
  },
  {
    title: 'Old town street-food walk',
    location: 'Lisbon, Portugal',
    description: 'Follow a local guide through Alfama’s lanes tasting pastéis de nata, bifanas and ginjinha while hearing the stories behind each family-run spot.',
    price_per_night: 45,
    rating: 4.88,
    review_count: 356,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
    category: 'City',
    property_type: 'experience',
    dates: '3 hours · daily',
    note: null,
  },
]

// Adventures — the outdoorsy, gear-and-guide end of the catalogue.
export const adventures = [
  {
    title: 'Guided glacier hike',
    location: 'Banff, Canada',
    description: 'Rope up with a certified mountain guide to cross a living glacier, learn to read crevasses and take in the Rockies from the ice. Crampons and gear included.',
    price_per_night: 140,
    rating: 4.97,
    review_count: 176,
    image_url: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?q=80&w=1200&auto=format&fit=crop',
    category: 'Mountains',
    property_type: 'adventure',
    dates: '6 hours · mornings',
    note: 'Rare find',
  },
  {
    title: 'Sunrise surf lesson',
    location: 'Canggu, Bali',
    description: 'Catch your first waves at dawn with an ISA-certified instructor on a mellow beach break. Board, rash guard and post-surf coconut all sorted.',
    price_per_night: 38,
    rating: 4.91,
    review_count: 512,
    image_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?q=80&w=1200&auto=format&fit=crop',
    category: 'Beach',
    property_type: 'adventure',
    dates: '2 hours · mornings',
    note: null,
  },
  {
    title: 'Sea kayaking through limestone karsts',
    location: 'Ha Long Bay, Vietnam',
    description: 'Paddle a stable sea kayak between towering karst islands, glide through hidden lagoons and caves, and picnic on a quiet beach you can only reach by water.',
    price_per_night: 66,
    rating: 4.89,
    review_count: 241,
    image_url: 'https://images.unsplash.com/photo-1526491109672-74740652b963?q=80&w=1200&auto=format&fit=crop',
    category: 'Islands',
    property_type: 'adventure',
    dates: '5 hours · daily',
    note: null,
  },
  {
    title: 'Desert dune 4x4 safari',
    location: 'Wadi Rum, Jordan',
    description: 'Bounce across red sand dunes with a Bedouin driver, scramble a rock arch, and finish with sweet tea and sunset over the valley made famous on film.',
    price_per_night: 85,
    rating: 4.95,
    review_count: 198,
    image_url: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?q=80&w=1200&auto=format&fit=crop',
    category: 'Countryside',
    property_type: 'adventure',
    dates: '4 hours · afternoons',
    note: 'Guest favorite',
  },
]

// The full catalogue used by the (destructive) full reseed.
export const properties = [...stays, ...experiences, ...adventures]

// Just the discovery rows, for the additive seed that preserves existing data.
export const discoveryProperties = [...experiences, ...adventures]
